server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:test
    username: user
    driver-class-name: org.h2.Driver


  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

app:
  kakao:
    rest-api-key: 3a59c84a1136c423f71d9219b71a2e72
  naver:
    client-id: 3a
    client-secret: 4d


